name: Liquibase_Docker_GitHub-Hosted

on:
  workflow_dispatch:
   push:
     branches: [ main ]

env:
    LIQUIBASE_PRO_LICENSE_KEY: ${{ secrets.LIQUIBASE_PRO_LICENSE_KEY }}
    LIQUIBASE_COMMAND_URL: ${{ secrets.LIQUIBASE_COMMAND_URL }}
    #${{ secrets.LB_USER }} 
    #${{ secrets.LB_URL }}
    #${{ secrets.LB_PASSWORD }}
    #${{ secrets.LB_DRIVER }} 
     
     #volumes: 
     #  - /github/workspace/changelogs:/liquibase/changelog
     #options: -v $GITHUB_WORKSPACE/changes:/liquibase/changelog

jobs:
  SnowflakeLBDocker:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    
    - name: Run 'Liquibase status' 	    
      uses: docker://liquibase/liquibase:snowflake
      with:
        #args: --url=${{ secrets.LB_URL }} --username=${{ secrets.LB_USER }} --password=${{ secrets.LB_PASSWORD }} --driver=${{ secrets.LB_DRIVER }} status --verbose
        args: checks run
        #args: --url=${{ secrets.LB_URL }} --username=${{ secrets.LB_USER }} --password=${{ secrets.LB_PASSWORD }} status --verbose

    
    #- name: Run 'Liquibase update' 
    #  uses: docker://liquibase/liquibase:latest
    #  with:
    #    args: --url=${{ secrets.LB_URL }} --changeLogFile=Bchanges/snowflake1.xml --username=${{ secrets.LB_USER }} --password=${{ secrets.LB_PASSWORD }} --driver=${{ secrets.LB_DRIVER }} update
